# Generated by Django 4.2.5 on 2023-12-03 08:38

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_name', models.CharField(blank=True, default=None, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Admin_Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_email', models.EmailField(blank=True, default=None, max_length=255, null=True)),
                ('employee_email', models.EmailField(blank=True, default=None, max_length=255, null=True)),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('max_warehouses', models.IntegerField(default=0, max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Bill_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('code', models.CharField(blank=True, default=None, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SuperAdmin_Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_email', models.EmailField(blank=True, default=None, max_length=255, null=True, verbose_name='super_admin_email')),
                ('admin_password', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='super_admin_passsword')),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warehouse_name', models.CharField(blank=True, default=None, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_name', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('warehouse_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_name', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('count', models.IntegerField()),
                ('count_type', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('shelf_number', models.IntegerField(default=1)),
                ('section_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.section')),
                ('warehouse_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('phone', models.IntegerField()),
                ('code', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('warehouse_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='Bill_final',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('code', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('material_name', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('count', models.IntegerField()),
                ('bill_details_id', models.IntegerField()),
                ('warehouse_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_name', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('count', models.IntegerField()),
                ('bill_details_id', models.IntegerField(default=-1)),
                ('warehouse_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.warehouse')),
            ],
        ),
    ]
